# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DbAction.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DbAction.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x44\x62\x41\x63tion.proto\"#\n\x11\x45xecutionResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x84\x01\n\x08\x44\x62\x41\x63tion\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x12\n\ntable_name\x18\x02 \x01(\t\x12\x11\n\tcol_names\x18\x03 \x03(\t\x12\x13\n\x0bvalues_json\x18\x04 \x01(\t\x12\x15\n\rkey_col_names\x18\x05 \x03(\t\x12\x17\n\x0fkey_values_json\x18\x06 \x01(\t2=\n\x0bReplication\x12.\n\tpropogate\x12\t.DbAction\x1a\x12.ExecutionResponse\"\x00(\x01\x62\x06proto3'
)




_EXECUTIONRESPONSE = _descriptor.Descriptor(
  name='ExecutionResponse',
  full_name='ExecutionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ExecutionResponse.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=53,
)


_DBACTION = _descriptor.Descriptor(
  name='DbAction',
  full_name='DbAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='DbAction.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='table_name', full_name='DbAction.table_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='col_names', full_name='DbAction.col_names', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='values_json', full_name='DbAction.values_json', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key_col_names', full_name='DbAction.key_col_names', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key_values_json', full_name='DbAction.key_values_json', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=188,
)

DESCRIPTOR.message_types_by_name['ExecutionResponse'] = _EXECUTIONRESPONSE
DESCRIPTOR.message_types_by_name['DbAction'] = _DBACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExecutionResponse = _reflection.GeneratedProtocolMessageType('ExecutionResponse', (_message.Message,), {
  'DESCRIPTOR' : _EXECUTIONRESPONSE,
  '__module__' : 'DbAction_pb2'
  # @@protoc_insertion_point(class_scope:ExecutionResponse)
  })
_sym_db.RegisterMessage(ExecutionResponse)

DbAction = _reflection.GeneratedProtocolMessageType('DbAction', (_message.Message,), {
  'DESCRIPTOR' : _DBACTION,
  '__module__' : 'DbAction_pb2'
  # @@protoc_insertion_point(class_scope:DbAction)
  })
_sym_db.RegisterMessage(DbAction)



_REPLICATION = _descriptor.ServiceDescriptor(
  name='Replication',
  full_name='Replication',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=190,
  serialized_end=251,
  methods=[
  _descriptor.MethodDescriptor(
    name='propogate',
    full_name='Replication.propogate',
    index=0,
    containing_service=None,
    input_type=_DBACTION,
    output_type=_EXECUTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_REPLICATION)

DESCRIPTOR.services_by_name['Replication'] = _REPLICATION

# @@protoc_insertion_point(module_scope)
